config/routes.rb
Microsites3Manager::Application.routes.draw do

  root 'welcome#home'

  devise_for :users, :controllers => {
    :sessions => "users/sessions",
    :registrations => 'users/registrations'
  }
  devise_scope :user do
    post 'sign_in', :to => 'users/sessions#create', :as => :session
  end

  resources :galleries

  resources :reports

  resources :tags

  resources :users

  namespace :manager do
    root :to => 'welcome#home'

    resources :cities do 
      resources :communities
      resources :events
      resources :features
      resources :galleries
      resources :newsitems
      resources :reports
      resources :users
      resources :venues
      resources :videos
    end

    get  'galleries_title',                 :to => 'galleries#index_title', :as => :galleries_title
    get  'galleries_thumb',                 :to => 'galleries#index_thumb', :as => :galleries_thumb
    get  'galleries_mini',                  :to => 'galleries#index_mini',  :as => :galleries_mini
    get  'galleries/j_show/:id',            :to => 'galleries#j_show',      :as => :j_gallery,        :defaults => { :format => :json }
    post 'galleries/:galleryname/multiadd', :to => 'photos#j_create',       :as => :photos_multiadd
    resources :galleries

    get 'photos/without_gallery', :to => 'photos#without_gallery', :as => :photos_without_gallery
    resources :photos
    # get 'photos/:id', :to => 'photos#show', :as => :photo
    # delete 'photos/:id', :to => 'photos#delete'
    
    # get 'reports', :to => 'reports#index', :as => :reports
    # post 'reports', :to => 'reports#create'
    get 'reports/without_site', :to => 'reports#index', :as => :reports_without_site, :site => false
    resources :reports
    
    get 'sites/:site_id/reports', :to => 'reports#index', :as => :site_reports
    get 'sites/trash', :to => 'sites#trash', :as => :sites_trash
    resources :sites do
      resources :newsitems
      resources :features
      resources :galleries
      resources :reports
      resources :vides
    end

    resources :tags do
      resources :features
      resources :newsitems

      resources :galleries
      resources :reports
      resources :videos
    end

    resources :users do
      resources :galleries
      resources :reports
      resources :videos
    end

    resources :venues do
    end

  end
  delete 'manager/sites/:site_id/newsitems/:newsitem_id', :to => 'manager/sites#newsitem_delete', :as => :manager_sites_newsitem
  # get 'manager/sites/:site_id/newsitems/:newsitem_id', :to => 'manager/sites#newsitem_show', :as => :manager_sites_newsitem

end

app/controllers/manager/cities_controller.rb
class Manager::CitiesController < Manager::ManagerController

  before_filter :set_lists, :only => [ :new_newsitem, :create_newsitem ]
  before_filter :sett_city, :only => [ :show, :edit ]

  def index
    authorize! :index, ManagerCity.new
    @cities = City.all
    @city = City.new
    @photo = Photo.new
  end
  
  def show
    authorize! :show, @city
  end
  
  def new
    authorize! :new, ManagerCity.new
    @city = City.new
    @photo = Photo.new
  end

  def create
    authorize! :create, ManagerCity.new
    @city = City.new params[:city].permit( :n_features, :n_newsitems, :x, :y, :is_feature, :cityname,
                                           :name_pt, :name_en, :name_ru, :name )
    
    if @city.save
      flash[:notice] = 'Success'
      redirect_to manager_cities_path
    else
      flash[:error] = 'No Luck'
      render :action => :new
    end
  end

  def edit
    authorize! :edit, @city
  end
  
  def update
    authorize! :update, ManagerCity.new

    @city = City.find( params[:id] )

    @city.update_attributes params[:city].permit!
    
    if @city.save
      flash[:notice] = 'Success'
      redirect_to edit_manager_city_path @city.id
    else
      flash[:error] = 'No Luck. ' + @city.errors.inspect
      @newsitems = @city.newsitems.all.page( params[:newsitems_page] )
      @features = @city.features.all.page( params[:features_page] )
      @photo = Photo.new
      render :action => :edit
    end
  end

  def change_profile_pic
    authorize! :change_profile_pic, ManagerCity.new

    @city = City.find params[:id]
    
    @photo = Photo.new params[:photo]
    @photo.user = @current_user
    flag = @photo.save
    @city.profile_photo = @photo
    flagg = @city.save
    if flag && flagg
      flash[:notice] = 'Success'
    else
      flash[:error] = "No Luck. #{@photo.errors.inspect} #{@city.errors.inspect}"
      # puts! @photo.errors.inspect
      # puts! @city.errors.inspect
    end

    redirect_to manager_cities_path
  end

  private

  def sett_city
    @city = City.find params[:id]
    @photo = Photo.new
  end

  def set_lists
    @list_reports = Report.all.list
    @list_galleries = Gallery.all.list
    @list_users = [['', nil]] + User.all.order_by( :name => :asc ).map { |u| [u.username, u.username] }
  end

end

app/controllers/manager/features_controller.rb
class Manager::FeaturesController < Manager::ManagerController

  before_filter :set_lists
  
  def new
    authorize! :new, ManagerFeature.new
    @city = City.find params[:city_id] unless params[:city_id].blank?
    @site = Site.find params[:site_id] unless params[:site_id].blank?
    @tag = Tag.find params[:tag_id] unless params[:tag_id].blank?
    @feature = Feature.new
  end

  def create
    authorize! :create, ManagerFeature.new

    @feature = Feature.new params[:feature].permit( :name, :subhead, :image_path, :link_path, :partial_name, :photo, :weight,
                                                    :report, :report_id, :gallery, :gallery_id, :video, :video_id
                                                  )
    if params[:city_id]
      @city = City.find params[:city_id]
      @city.features << @feature
      redirect_path = manager_cities_path
    end
    if params[:site_id]
      @site = Site.find params[:site_id]
      @site.features << @feature
      redirect_path = manager_sites_path
    end
    if params[:tag_id]
      @tag = Tag.find params[:tag_id]
      @tag.features << @feature
      redirect_path = manager_tags_path
    end

    if (@city && @city.save) || (@site && @site.save) || (@tag && @tag.save)
      flash[:notice] = 'Success.'
      redirect_to redirect_path
    else
      flash[:error] = 'No Luck. ' + ( @city || @site || @tag ).errors.inspect
      render :action => :new
    end
  end

  def edit
    authorize! :edit, ManagerCity.new
    
    if params[:city_id]
      @city = City.find params[:city_id]
      @feature = @city.features.find params[:id]
    end

    if params[:site_id]
      @site = Site.find params[:site_id]
      @feature = @site.features.find params[:id]
    end

    if params[:tag_id]
      @tag = Tag.find params[:tag_id]
      @feature = @tag.features.find params[:id]
    end
   
    if params[:venue_id]
      @venue = Tag.find params[:venue_id]
      @feature = @venue.features.find params[:id]
    end

  end

  def update
    unless params[:city_id].blank?
      @city = City.find params[:city_id] 
      authorize! :update, ManagerCity.new
      @feature = @city.features.find params[:id]
      redirect_path = manager_city_path( @city )
    end
    unless params[:site_id].blank?
      @site = Site.find params[:site_id] 
      authorize! :update, ManagerSite.new
      @feature = @site.features.find params[:id]
      redirect_path = manager_site_path( @site )
    end
    unless params[:tag_id].blank?
      @tag = Tag.find params[:tag_id]
      authorize! :update, ManagerTag.new
      @feature = @tag.features.find params[:id]
      redirect_path = manager_tag_path( @tag )
    end
    
    if @feature.update_attributes params[:feature].permit!
      flash[:notice] = 'Success'
      redirect_to redirect_path
    else
      flash[:error] = 'No Luck. ' + @feature.errors.inspect
      puts! @feature.errors, 'Errors updating feature'
      render :action => :edit_feature
    end    
  end

  def index
    if params[:tag_id]
      @resource = Tag.find params[:tag_id]
    end
    
  end

  def destroy
    if params[:tag_id]
      @resource = Tag.find params[:tag_id]
    elsif params[:city_id]
      @resource = City.find params[:city_id]
    elsif params[:site_id]
      @resource = Site.find params[:site_id]
    end
    @feature = @resource.features.find params[:id]
    if @feature.destroy
      flash[:notice] = :'Success.' 
    else
      flash[:error] = :'No luck.'
    end
    redirect_to request.referrer
  end
  
end

app/controllers/manager/galleries_controller.rb
class Manager::GalleriesController < Manager::ManagerController

  before_filter :set_lists
  
  def index
    redirect_to manager_galleries_thumb_path
  end

  def index_title
    @galleries = Gallery.unscoped.where( :is_trash => false ).order_by( :created_at => :desc )
  end

  def index_thumb
    @galleries = Gallery.unscoped.where( :is_trash => false ).order_by( :created_at => :desc ).page( params[:galleries_page] ).per( 10 )
  end

  def index_mini
    @galleries = Gallery.all
  end

  def new
    @gallery = Gallery.new
    @cities_list = City.list
    @tags_list = Tag.list
  end

  def create
    @gallery = Gallery.new params[:gallery].permit!
    @gallery.user = current_user
    authorize! :create, @gallery

    if @gallery.save
      flash[:notice] = 'Success'
      redirect_to manager_galleries_path
    else
      flash[:error] = 'No Luck. ' + @gallery.errors.inspect
      @cities_list = City.list
      @tags_list = Tag.list
      render :action => 'new'
    end
  end

  def edit
    @gallery = Gallery.unscoped.find params[:id]
  end

  def update
    @gallery = Gallery.unscoped.find params[:id]
    if @gallery.update_attributes( params[:gallery].permit( :username, :name, :galleryname, :subhead, :descr, :lang,
                                                            :is_trash, :is_public, :is_done, :is_feature,
                                                            :tag_id, :city_id, :venue_id, :site_id, :user_id, :site_id ) )
      flash[:notice] = 'Success.'
      redirect_to manager_galleries_path
    else
      flash[:error] = 'No Luck. ' + @gallery.errors
      render :action => :edit
    end
  end                           

  def show
    @gallery = Gallery.unscoped.find params[:id]
    @photos = @gallery.photos.unscoped.where({ :is_trash => false })
  end

  def destroy
    @gallery = Gallery.unscoped.find params[:id]
    @gallery.is_trash = true
    @gallery.save
    flash[:notice] = 'Logically deleted gallery.'
    redirect_to manager_galleries_title_path
  end

  def j_show
    @gallery = Gallery.unscoped.find( params[:id] )
    authorize! :show, @gallery
    respond_to do |format|
      format.json do
        jjj = {}
        jjj[:photos] = @gallery.photos.map do |ph|
          { :thumbnail_url => ph.photo.url( :thumb ),
          :delete_type => 'DELETE',
          :delete_url => photo_path(ph) }
        end
        render :json => jjj
      end
    end
  end

end

app/controllers/manager/manager_controller.rb
class Manager::ManagerController < ApplicationController

  layout 'manager'

  prepend_before_action :authenticate_user!
  before_action :validate_manager
  before_action :do_set

  private

  def validate_manager
    if 'piousbox' == current_user['username'] || 'manager' == current_user['username']
      return true
    else
      redirect_to root_path
    end
  end

  def set_lists
    @tags_list = Tag.all.list
    @sites_list = Site.all.list
    @cities_list = City.all.list
    @venues_list = Venue.all.list
    @users_list = User.all.list
    
    @reports_list = Report.all.list
    @galleries_list = Gallery.all.list
    @videos_list = Video.all.list
  end

  def do_set
    @latest_changelog = File.read( Rails.root.join('changelog.txt') ).split("\n").last
    @branch = `git branch | grep -e "^*" | cut -d' ' -f 2`
  end

end

app/controllers/manager/newsitems_controller.rb
class Manager::NewsitemsController < Manager::ManagerController

  def new
    authorize! :new, ManagerNewsitem.new
    @newsitem = Newsitem.new
    if params[:city_id]
      @city = City.find params[:city_id]
      @newsitem.city = @city
    end
    if params[:site_id]
      @site = Site.find params[:site_id]
      @newsitem.site = @site
    end
  end

  def create
    authorize! :create, ManagerNewsitem.new

    n = Newsitem.new params[:newsitem].permit!
    n.report  = Report.find  params[:newsitem][:report_id]  unless params[:newsitem][:report_id].blank?
    n.gallery = Gallery.find params[:newsitem][:gallery_id] unless params[:newsitem][:gallery_id].blank?
    n.photo   = Photo.find   params[:newsitem][:photo_id]   unless params[:newsitem][:photo_id].blank?
    n.descr   = params[:newsitem][:descr]

    if params[:city_id]
      @city = City.find params[:city_id]
      @city.newsitems << n
      flag = @city.save
      if flag
        url = edit_manager_city_path( @city.id )
      else
        error = 'No Luck. ' + @city.errors.inspect
      end
    end
    
    if params[:site_id]
      @site = Site.find params[:site_id]
      @site.newsitems << n
      flag = @site.save
      if flag
        url = edit_manager_site_path( @site.id )
      else
        error = 'No Luck. ' + @site.errors.inspect
      end
    end

    if flag
      flash[:notice] = 'Success'
      redirect_to url
    else
      flash[:error] = error
      render :action => :new
    end
  end
  
  def show
  end

  def index
  end

  def destroy
    if params[:city_id]
      flag = City.find( params[:city_id] ).newsitems.find( params[:id] ).destroy
      url = edit_manager_city_path( params[:city_id] )
    end
    if params[:site_id]
      site = Site.find( params[:site_id] )
      flag = site.newsitems.find( params[:id] ).destroy
      url = edit_manager_site_path( params[:site_id] )
    end

    flash[:notice] = "Success? #{flag}"
    redirect_to url
  end

  def update
    if params[:site_id]
      @site = Site.find params[:site_id]
      @site.touch
      @newsitem = @site.newsitems.find params[:id]
      url = edit_manager_site_path( @site )
    end
    if params[:city_id]
      @city = City.find params[:city_id]
      @newsitem = @city.newsitems.find params[:id]
      url = edit_manager_city_path( @city )
    end
    flag = @newsitem.update_attributes params[:newsitem].permit!
    
    if flag
      flash[:notice] = 'Success'
    else
      flash[:error] = "No Luck: #{@newsitem.errors.messages}"
    end

    redirect_to url
  end
  
  def edit
    if params[:site_id]
      @site = Site.find params[:site_id]
      @newsitem = @site.newsitems.find( params[:id] )
    end
    if params[:city_id]
      @city = City.find params[:city_id]
      @newsitem = @city.newsitems.find( params[:id] )
    end
  end

end

app/controllers/manager/photos_controller.rb
class Manager::PhotosController < Manager::ManagerController

  # @TODO: this is bad? _vp_ 20170513
  skip_authorization_check :only => [ :j_create ]
  protect_from_forgery :except => [ :j_create] 

  def without_gallery
    @photos = Photo.unscoped.where( :gallery => nil, :is_trash => false )
  end

  def destroy
    @photo = Photo.unscoped.find params[:id]
    @photo.is_trash = true
    @photo.save
    redirect_to request.referrer
  end

  def show
    @photo = Photo.unscoped.find params[:id]
  end

  def j_create
    @photo = Photo.new params[:photo].permit!
    authorize! :create, @photo
    @photo.is_public = true
   
    if params[:galleryname]
      gallery = Gallery.unscoped.where( :galleryname => params[:galleryname] ).first
      @photo.gallery_id = gallery.id
    elsif params[:gallery_id]
      gallery = Gallery.find( params[:gallery_id] )
      @photo.gallery_id = gallery.id
    end
   
    # @TODO this is badd
    @photo.user = User.where( :username => 'piousbox' ).first

    if @photo.save
      j = { :name => @photo.photo.original_filename,
        :size => @photo.photo.size,
        :url => @photo.photo.url( :large ),
        :thumbnail_url => @photo.photo.url( :thumb ),
        :delete_url => photo_path(@photo),
        :delete_type => 'DELETE',
        :name => @photo.name
      }
      render :json => [ j ]
    else
      render :json => { "errors" => @photo.errors } 
    end
  end

end

app/controllers/manager/tags_controller.rb
class Manager::TagsController < Manager::ManagerController

  before_filter :set_lists

  def index
    @tags = Tag.unscoped
    authorize! :index, Tag.new
  end
  
  def show
    @tag = Tag.unscoped.find params[:id]
    authorize! :show, @tag
  end

  def new
    @tag = Tag.new
    authorize! :new, @tag
  end

  def create
    @tag = Tag.create params[:tag].permit( :name, :name_seo, :descr, :is_public, :is_feature, :is_trash,
                                           :weight, :parent_tag_id, :site_id )
    authorize! :create, @tag
    if @tag.save
      flash[:notice] = 'Success.'
      redirect_to manager_tags_path
    else
      puts! @tag.errors, "error creating tag."
      flash[:error] = "No luck. #{@tag.errors.messages}" 
      render :action => :new
    end
  end

  def edit
    @tag = Tag.unscoped.find params[:id]
    authorize! :edit, @tag
  end

  def update
    @tag = Tag.unscoped.find params[:id]
    authorize! :update, @tag
    if @tag.update_attributes params[:tag].permit( :name, :name_seo, :descr,
                                                   :is_public, :is_trash, :is_feature, :weight,
                                                   :site_id, :parent_tag_id )
      flash[:notice] = 'Success.'
      redirect_to manager_tags_path
    else
      flash[:error] = 'No luck.'
      render :action => :new
    end
  end
  
end

app/controllers/manager/users_controller.rb
class Manager::UsersController < Manager::ManagerController

  def index
    @users = User.all
  end

  def show
    @user = User.find params[:id]
  end

end

app/views/manager/cities/_form.haml
- url ||= manager_cities_path

.manager-cities--form
  = form_for @city, :url => url do |f|
    .row
      .small-6.columns
        .field
          %label= t('cities.name')
          = f.text_field :name
        .field
          = image_flag 'en'
          %label= t('cities.name_en')
          = f.text_field :name_en
        .field
          = image_flag 'ru'
          %label= t('cities.name')
          = f.text_field :name_ru
        .field
          = image_flag 'pt'
          %label= t('cities.name')
          = f.text_field :name_pt
        .field
          %label CityName
          = f.text_field :cityname
      .small-6.columns
        .field
          %label Feature?
          = f.check_box :is_feature
        .field
          = f.label :n_features
          = f.number_field :n_features
          
        .field
          %label Calendar
          = f.text_area :calendar_frame
        .field
          %label coords
          = f.text_field :x
          = f.text_field :y
                    
        -# Only if editing 
        - unless @city.updated_at.blank?  
          .change-profile-pic
            %h2 Change profile pic
            - begin
              = image_tag @city.profile_photo.photo.url(:thumb)
            - rescue
              
        .actions
          = f.submit

app/views/manager/cities/_header.haml
%h1
  = t('list.cities')
  = link_to '[+]', new_manager_city_path

app/views/manager/cities/_meta.haml
.cities-meta
  = "(#{city.reports.length}) (#{city.galleries.length}) (#{city.current_users.length})"

app/views/manager/cities/edit.haml
%h1.center= @city.name
= render 'form', :url => manager_city_path
%hr

.row
  .small-12.columns
    = render 'manager/features/index', :features => @city.features, :city => @city
%hr
= render 'manager/newsitems/index', :newsitems => @city.newsitems, :city => @city

app/views/manager/cities/edit_feature.haml
%h1 Edit Feature of city #{@city.name}

= render 'manager/features/form', :url => city_feature_path(@city.id, @feature.id)

app/views/manager/cities/index.haml
.row
  .large-12.columns
    = render 'manager/cities/header'

    %ul.large-block-grid-4
      - @cities.each do |city|
        %li
          = link_to city.name, manager_city_path(city)
          = link_to '[~]', edit_manager_city_path(city)

          = render 'manager/cities/meta', :city => city
          .small.gray= city.id
      
          - if city.profile_photo.blank?
            = image_missing
          - else
            = image_tag city.profile_photo.photo.url(:thumb)

app/views/manager/cities/new.haml
.row
  .large-12.columns
    %h1 New City
    = render 'form'

app/views/manager/cities/new_feature.haml
%h2 New Feature for #{@city.name}

= render 'manager/features/form', :url => create_city_feature_path(@city.id)

app/views/manager/cities/new_newsitem.haml
%h1 Newsitem for #{@city.name}

= form_for @newsitem, :url => manager_city_newsitems_path(@city.cityname) do |f|

  .field
    %label descr
    = f.text_area :descr, :class => 'tinymce tiny_mce'

  .field
    %label Report
    = select :newsitem, :report_id, @list_reports

  .field
    %label Gallery
    = select :newsitem, :gallery_id, @list_galleries

  .field
    %label User
    = select :newsitem, :username, @list_users


  = f.submit

app/views/manager/cities/show.haml
- title "City #{@city.name}"

.row
  .large-12.columns

    %h2
      = @city.name
      = link_to '[~]', edit_manager_city_path(@city)

    - unless @city.profile_photo.blank?
      = image_tag @city.profile_photo.photo.url(:thumb)

    %hr
    %ul.menu-secondary
      %li
        = link_to '[+]', new_manager_city_feature_path( @city )
        Features (#{@city.features.length})
      %li
        = link_to '[+]', new_manager_city_newsitem_path( @city )
        Newsitems (#{@city.newsitems.length})
      %li New Report
      %li New Gallery
      %li New Video
      %li New Venue
      %li New Event
      %li New Community
    %hr

    = render 'manager/features/index', :features => @city.features, :city => @city
    = render 'manager/newsitems/index', :newsitems => @city.newsitems, :city => @city
    
    %h3
      = t('reports.list')
      (#{@city.reports.length})
    %ul
      - @city.reports.each do |report|
        %li
          = link_to '[~]', edit_manager_report_path(report)
          = report.name

    .galleries-list
      %h3
        = t('galleries.list')
        (#{@city.galleries.length})
      = render '/manager/galleries/list_short', :galleries => @city.galleries

    %h3
      = t('users.list')
      (#{@city.current_users.length})
      
    %h3 Events (#{@city.events.length})
    %ul
      - @city.events.each do |event|
        %li= event.name
        
    %h3 Venues (#{@city.venues.length})
    %h3 Videos (#{@city.videos.length})