config/routes.rb
Microsites3Manager::Application.routes.draw do

  root 'welcome#home'

  devise_for :users, :controllers => {
    :sessions => "users/sessions",
    :registrations => 'users/registrations'
  }
  devise_scope :user do
    post 'sign_in', :to => 'users/sessions#create', :as => :session
  end

  resources :galleries

  resources :reports

  resources :tags

  resources :users

  namespace :manager do
    root :to => 'welcome#home'

    resources :cities do 
      resources :communities
      resources :events
      resources :features
      resources :galleries
      resources :newsitems
      resources :reports
      resources :users
      resources :venues
      resources :videos
    end

    get  'galleries_title',                 :to => 'galleries#index_title', :as => :galleries_title
    get  'galleries_thumb',                 :to => 'galleries#index_thumb', :as => :galleries_thumb
    get  'galleries_mini',                  :to => 'galleries#index_mini',  :as => :galleries_mini
    get  'galleries/j_show/:id',            :to => 'galleries#j_show',      :as => :j_gallery,        :defaults => { :format => :json }
    post 'galleries/:galleryname/multiadd', :to => 'photos#j_create',       :as => :photos_multiadd
    resources :galleries

    get 'photos/without_gallery', :to => 'photos#without_gallery', :as => :photos_without_gallery
    resources :photos
    # get 'photos/:id', :to => 'photos#show', :as => :photo
    # delete 'photos/:id', :to => 'photos#delete'
    
    # get 'reports', :to => 'reports#index', :as => :reports
    # post 'reports', :to => 'reports#create'
    get 'reports/without_site', :to => 'reports#index', :as => :reports_without_site, :site => false
    resources :reports
    
    get 'sites/:site_id/reports', :to => 'reports#index', :as => :site_reports
    get 'sites/trash', :to => 'sites#trash', :as => :sites_trash
    resources :sites do
      resources :newsitems
      resources :features
      resources :galleries
      resources :reports
      resources :vides
    end

    resources :tags do
      resources :features
      resources :newsitems

      resources :galleries
      resources :reports
      resources :videos
    end

    resources :users do
      resources :galleries
      resources :reports
      resources :videos
    end

    resources :venues do
    end

  end
  delete 'manager/sites/:site_id/newsitems/:newsitem_id', :to => 'manager/sites#newsitem_delete', :as => :manager_sites_newsitem
  # get 'manager/sites/:site_id/newsitems/:newsitem_id', :to => 'manager/sites#newsitem_show', :as => :manager_sites_newsitem

end

app/views/videos/_embed.erb
<div class="video-embed">
  <iframe width="560" height="315" src="http://www.youtube.com/embed/<%= video.youtube_id %>" frameborder="0" allowfullscreen></iframe>
</div>

app/views/videos/_embed_half.erb
<div class="video-embed-half">
  <iframe width="430" height="322" src="http://www.youtube.com/embed/<%= video.youtube_id %>" frameborder="0" allowfullscreen></iframe>
</div>

app/views/videos/_form.haml
- url ||= videos_path
= form_for @video, :url => url do |f|

  = render 'application/form_errors', :item => @video
 
  .field
    = f.label :youtube_id
    = f.text_field :youtube_id

  .field
    = f.label :name
    = f.text_field :name

  .field
    = f.label :tag_id
    = select :video, :tag_id, @tags_list

  .field
    = f.label :city_id
    = select :video, :city_id, @cities_list

  -# .field
  -#   = f.label :descr
  -#   = f.text_field :descr

  .action
    = f.submit

app/views/videos/_list.haml
.videos-list
  - if videos.blank?
    =t ('videos.no_videos')
  - else
    - videos.each do |video|
      .a
        %h5= link_to (video.name.blank? ? t('videos.no_title') : video.name), video_path( video.youtube_id )
        .text-center= render 'videos/embed', :video => video
        = video.descr
    = paginate videos, :param_name => :videos_page
  .c
.c

app/views/videos/_list_small.haml
.list-small
  %ul
    - videos.each do |v|
      %li= image_tag( "http://img.youtube.com/vi/#{v.youtube_id}/1.jpg" )
    - if 0 == @my_videos.length
      %li= t('videos.no_videos')

app/views/videos/index.haml
.row
  .large-12.columns
    .title
      %h1= t('videos.list')

    .center= render 'ads/src/leaderboard'    

    = render 'videos/list', :videos => @videos

    .center= render 'ads/src/leaderboard'    

app/views/videos/new.haml
%h2= t('videos.new')
= render 'videos/form'

app/views/videos/show.haml
.row
  .large-12.columns

    %h3
      - if @video.name.blank?
        = t('videos.no_title')
      - else
        = @video.name
    = render 'application/meta', :item => @video
    .text-center= render 'embed', :video => @video


    = render 'disqus'